import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

import Header from "../components/molecules/Header";
import Footer from "../components/molecules/Footer";
import BgCanvas from "../components/molecules/RTF/BgCanvas";
import SmoothScrollProvider from "../components/atoms/SmoothScrollProvider";

const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // IBM Plex Sans weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          bg-[#020311]
          relative
          ${plexSans.variable}
          antialiased
        `}
      >
        <BgCanvas />
       <SmoothScrollProvider><div className="h-[200vh]">
        
        <div className="w-[800px] h-[500px] my-[150px] bg-[rgba(155,155,155,0.1)] mx-auto border-2 border-[rgba(255,255,255,0.1)] rounded-xl backdrop-blur-xl"></div>
        <div className="w-[800px] h-[500px] my-[150px]"></div>
        <div className="w-[800px] h-[500px] my-[150px] bg-[rgba(155,155,155,0.1)] mx-auto border-2 border-[rgba(255,255,255,0.1)] rounded-xl backdrop-blur-xl"></div>
        <div className="w-[800px] h-[500px] my-[150px]"></div>
        </div></SmoothScrollProvider> 
        {/*<Header />
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
        <Footer />*/}
      </body>
    </html>
  );
}
