import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

import Header from "../components/molecules/Header";
import Footer from "../components/molecules/Footer";
import BgCanvas from "../components/molecules/RTF/BgCanvas";
import SmoothScrollProvider from "../components/atoms/SmoothScrollProvider";

const plexSans = IBM_Plex_Sans({
  variable: "--font-plex-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // IBM Plex Sans weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          bg-slate-950
          relative
          ${plexSans.variable}
          antialiased
        `}
      >
        <BgCanvas />
        <Header />
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
        <Footer />
      </body>
    </html>
  );
}
